# Generated by Django 5.1 on 2024-08-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='bio',
            new_name='descricao',
        ),
    ]
